spring.application.name=earthquake-app
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/earthquake_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.connection-timeout=20000

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

usgs.api.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
